### ISSUE TITLE
TypeError when not passing optional parameter intensity

### ISSUE THREAD

**Issue by Iwijn** [jrussell25/dask-regionprops#4]
* dask-regionprops version: 0.3.0
* Python version: 3.9.7
* Operating System: CentOS Linux 7 (Core)

### Description

When using regionprops on an array with no intensity given a TypeError is thrown while this parameter is optional.

### What I Did

```
from dask_regionprops import regionprops
example_array = da.zeros(100).reshape((10,10))
regionprops(example_array)
```
![2022-06-03-003705_1039x376_scrot](https://user-images.githubusercontent.com/30521286/171750002-508e171e-51a8-4d7f-bb2e-64a731260390.png)

**Comment by jrussell25** [comment]
Should be all good in version `0.3.1`
